spring:
#management:
#  security:
#    enable:false
#server:
  #ssl:
    #key-store: classpath:keystore.jks
    #key-store-password: password
    #key-store-type: JKS
    #keu-alias: linkedin
    #key-password: password

#spring.datasource.initialization-mode=embedded
  jpa:
    hibernate:
      ddl-auto: none
---
spring:
  profiles: dev
server:
  port: 8000
---
spring:
  profiles: test

server:
  port: 9000
