spring:
#management:
#  security:
#    enable:false
#server:
  #ssl:
    #key-store: classpath:keystore.jks
    #key-store-password: password
    #key-store-type: JKS
    #keu-alias: linkedin
    #key-password: password

#spring.datasource.initialization-mode=embedded
  jpa:
    hibernate:
      ddl-auto: none

amqp:
  queue:
    name: room-cleaner
  exchange:
    name: landom-rooms-exchange

landon:
  logging:
    logger-name: LinkedinLearning-Landon
---
spring:
  profiles: dev
server:
  port: 8000
---
spring:
  profiles: test

server:
  port: 9000
